// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package metricspb_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsClient interface {
	CreateCounter(ctx context.Context, in *CreateCounterParams, opts ...grpc.CallOption) (*Response, error)
	CreateGauge(ctx context.Context, in *CreateGaugeParams, opts ...grpc.CallOption) (*Response, error)
	CreateHistogram(ctx context.Context, in *CreateHistogramParams, opts ...grpc.CallOption) (*Response, error)
	CounterInc(ctx context.Context, in *UpdateParams, opts ...grpc.CallOption) (*Response, error)
	GaugeSet(ctx context.Context, in *UpdateParams, opts ...grpc.CallOption) (*Response, error)
	HistogramObserve(ctx context.Context, in *UpdateParams, opts ...grpc.CallOption) (*Response, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) CreateCounter(ctx context.Context, in *CreateCounterParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Metrics/CreateCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) CreateGauge(ctx context.Context, in *CreateGaugeParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Metrics/CreateGauge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) CreateHistogram(ctx context.Context, in *CreateHistogramParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Metrics/CreateHistogram", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) CounterInc(ctx context.Context, in *UpdateParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Metrics/CounterInc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) GaugeSet(ctx context.Context, in *UpdateParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Metrics/GaugeSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) HistogramObserve(ctx context.Context, in *UpdateParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Metrics/HistogramObserve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility
type MetricsServer interface {
	CreateCounter(context.Context, *CreateCounterParams) (*Response, error)
	CreateGauge(context.Context, *CreateGaugeParams) (*Response, error)
	CreateHistogram(context.Context, *CreateHistogramParams) (*Response, error)
	CounterInc(context.Context, *UpdateParams) (*Response, error)
	GaugeSet(context.Context, *UpdateParams) (*Response, error)
	HistogramObserve(context.Context, *UpdateParams) (*Response, error)
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (UnimplementedMetricsServer) CreateCounter(context.Context, *CreateCounterParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCounter not implemented")
}
func (UnimplementedMetricsServer) CreateGauge(context.Context, *CreateGaugeParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGauge not implemented")
}
func (UnimplementedMetricsServer) CreateHistogram(context.Context, *CreateHistogramParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHistogram not implemented")
}
func (UnimplementedMetricsServer) CounterInc(context.Context, *UpdateParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CounterInc not implemented")
}
func (UnimplementedMetricsServer) GaugeSet(context.Context, *UpdateParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GaugeSet not implemented")
}
func (UnimplementedMetricsServer) HistogramObserve(context.Context, *UpdateParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistogramObserve not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_CreateCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCounterParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).CreateCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Metrics/CreateCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).CreateCounter(ctx, req.(*CreateCounterParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_CreateGauge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGaugeParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).CreateGauge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Metrics/CreateGauge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).CreateGauge(ctx, req.(*CreateGaugeParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_CreateHistogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHistogramParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).CreateHistogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Metrics/CreateHistogram",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).CreateHistogram(ctx, req.(*CreateHistogramParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_CounterInc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).CounterInc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Metrics/CounterInc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).CounterInc(ctx, req.(*UpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_GaugeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GaugeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Metrics/GaugeSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GaugeSet(ctx, req.(*UpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_HistogramObserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).HistogramObserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Metrics/HistogramObserve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).HistogramObserve(ctx, req.(*UpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCounter",
			Handler:    _Metrics_CreateCounter_Handler,
		},
		{
			MethodName: "CreateGauge",
			Handler:    _Metrics_CreateGauge_Handler,
		},
		{
			MethodName: "CreateHistogram",
			Handler:    _Metrics_CreateHistogram_Handler,
		},
		{
			MethodName: "CounterInc",
			Handler:    _Metrics_CounterInc_Handler,
		},
		{
			MethodName: "GaugeSet",
			Handler:    _Metrics_GaugeSet_Handler,
		},
		{
			MethodName: "HistogramObserve",
			Handler:    _Metrics_HistogramObserve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metricspbV1.proto",
}
